// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5ex8ZinboQKqVH_x5fUj40eayUrpcAQ',
    appId: '1:5169050914:web:619ee24345f35f5df3e17b',
    messagingSenderId: '5169050914',
    projectId: 'fintrack-ec-2025',
    authDomain: 'fintrack-ec-2025.firebaseapp.com',
    storageBucket: 'fintrack-ec-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHhuErMbuP4kj7h9dNI3exw5UB0HpXE-s',
    appId: '1:5169050914:android:6145a9f825a40942f3e17b',
    messagingSenderId: '5169050914',
    projectId: 'fintrack-ec-2025',
    storageBucket: 'fintrack-ec-2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5ex8ZinboQKqVH_x5fUj40eayUrpcAQ',
    appId: '1:5169050914:web:19ed74c04a7ed5e7f3e17b',
    messagingSenderId: '5169050914',
    projectId: 'fintrack-ec-2025',
    authDomain: 'fintrack-ec-2025.firebaseapp.com',
    storageBucket: 'fintrack-ec-2025.firebasestorage.app',
  );

}